### This guide is meant to outline the procedure for installing the Nginx Ingress Controller and MetalLB load balancer on a running SUSE CaaS Platform installation on an on-premesis compute infrastructure. A follow on document specfically covers preparing this cluster for installing SUSE Cloud Application Platform using these resources

NOTE: This guide follows a methodology of populating a single variables file for the entire operation and then sourcing that file at the beginning of each major step.

ATTENTION: This guide assumes a SUSE CaaS Platform cluster is fully installed and running on an on-premesis compute infrastructure and DNS service for the cluster nodes. The Kubernetes applications, including SUSE CAP, require additional resources such as a default Storage Class to be configured.

NOTE: Specifically for supporting SUSE CAP, a wild-card DNS record that matches the SVC_FQDN below must be created as part of the CAP deployment process. This procedure enables associating the SVC_FQDN with the first IP address in the load balancers range of reserved IP addresses (DEFAULT_IP_RANGE_START)

### Create and populate a variables file (i.e. ngnix-metallb.vars) on the administrative workstation from which the kubectl and helm commands will be run:

NOTE: The following steps will create a local Certificate Authority and self-signed TLS certificate. They are not applicable for using a certificate from a public CA or exisitng private CA.

TIP: These variables can be populated and used to generate the root CA private key and x509 cerficate, then updated to create the site (application) private key and certificate; or the same information can be used for both (only for testing and sandbox environments).

----
### START Variables for creating the TSL certificates and keys ###
### IMPORTANT: Spaces are not allowed in any field!
# Name of the root CA
export ROOTCA_NAME=
# (OPTIONAL) Take note of the root CA cert passphrase here 
ROOTCA_PASSPHRASE=
## Document the values to used in creating the root CA certificate:
# Two letter country code
export COUNTRY_NAME=
# State or Province
export STATE_NAME=
# Locality or City
export LOCALITY_NAME=
# Major organization or company
export ORGANIZATION_NAME=
# OU or section
export ORGANIZATIONAL_UNIT_NAME=
# Server FQDN or service domain name, i.e. scf.caasp.local
export COMMON_NAME=
export EMAIL_ADDRESS=
# The FQDN of the external URL that clients will connect to, can be the same a COMMON_NAME in some environments
export SVC_FQDN=
### END Variables for creating the TSL/SSL certificates and keys ###

### START Variables for instantiating the MetalLB load balancer ###
# For this configuration IP range will be configured as START-END, 
# i.e. 10.0.0.10-10.0.0.19 or 10.0.0.10-10.0.0.10. It can also be expressed as IP/CIDR, 
# though the metallb-config.yaml and nginx-metallb-test.yaml files would have be adjusted 
# slightly from these instructions
# Two IP address pools will be configured, the default pool for all non-CAP services, and the suse-cloud-application-platform pool (which needs only one IP address by default)
export DEFAULT_IP_RANGE_START=
export DEFAULT_IP_RANGE_END=
export CAP_IP_RANGE_START=
export CAP_IP_RANGE_END=

----



### Create the TLS certificates and keys

.Source the variables file (i.e. `source ngnix-metallb.vars`), then run the following commands


* Generate the 2048 bit root CA private key using des3 encryption
** Set the root CA private key passphrase when prompted
----
openssl genrsa -des3 -out ${ROOTCA_NAME}.key 2048
----

* Generate the root CA TLS certificate
** Provide the root CA private key passphrase to generate the root CA public key from the root CA private key
----
openssl req -x509 -new -nodes -key ${ROOTCA_NAME}.key  -subj "/C=${COUNTRY_NAME}/ST=${STATE_NAME}/L=${LOCALITY_NAME}/O=${ORGANIZATION_NAME}/OU=${ORGANIZATIONAL_UNIT_NAME}/CN=${COMMON_NAME}/emailAddress=${EMAIL_ADDRESS}" -sha256 -days 1825 -out ${ROOTCA_NAME}.pem
----

* (Optional): Verify the contents of the root CA TLS certificate: `openssl x509 -noout -text -in ${ROOTCA_NAME}.pem  | less`

NOTE: What makes this a root CA is that the `Subject Key Identifier` and the `Authority Key Identifier` are the same, meaning there is no authority higher than this CA.

TIP: If different information is required (i.e. Subject name, OU, email address) for the site certificate, update the variables file (DON'T FORGET TO SOURCE IT!) before continuing.

* Generate the 2048 bit site (aka Subjet) private key using RSA encryption
----
openssl genrsa -out ${SVC_FQDN}.key 2048
----

* Generate the site certificate signing request
----
openssl req -new -key ${SVC_FQDN}.key -subj "/C=${COUNTRY_NAME}/ST=${STATE_NAME}/L=${LOCALITY_NAME}/O=${ORGANIZATION_NAME}/OU=${ORGANIZATIONAL_UNIT_NAME}/CN=${COMMON_NAME}/emailAddress=${EMAIL_ADDRESS}" -out ${SVC_FQDN}.csr
----

* (Optional): Verify the contents of the Certificate Signing Request: `openssl req -noout -text -in ${SVC_FQDN}.csr | less`

NOTE: The CSR is little more than identifying information for the subject (the entity requesting a TLS cert), the primary URL that the TLS cert will cover, and the public key for it.

* Create the extensions file. This is used to enhance the resulting TLS certificate with extra features such as Subject Alternaete Names that this certificate will cover (Note that a single private/public key pair will be used by the primary site and all of the sites listed here):
----
cat <<EOF> ${SVC_FQDN}.ext
authorityKeyIdentifier=keyid,issuer

basicConstraints=CA:FALSE

keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment

subjectAltName = @alt_names

[alt_names]

DNS.1 = ${SVC_FQDN}

DNS.2 = *.${SVC_FQDN}

DNS.3 = uaa.${SVC_FQDN}

DNS.4 = *.uaa.${SVC_FQDN}
EOF
----
* Create the site TLS (x509) certificate
** Provide the root CA private key passphrase when prompted
----
openssl x509 -req -in ${SVC_FQDN}.csr -CA ${ROOTCA_NAME}.pem -CAkey ${ROOTCA_NAME}.key -CAcreateserial -out ${SVC_FQDN}.crt -days 1825 -sha256 -extfile ${SVC_FQDN}.ext
----

* (OPTIONAL) Verify the site certificate public key, site private key, and certificate signing request files were created correctly and all match
** The resulting md5 hashes should all be the same
----
openssl x509 -noout -modulus -in ${SVC_FQDN}.crt | openssl md5
openssl rsa -noout -modulus -in ${SVC_FQDN}.key | openssl md5
openssl req -noout -modulus -in ${SVC_FQDN}.csr | openssl md5
----


### Deploy the MetalLB load balancer

.Source the variables file (i.e. `source ngnix-metallb.vars`), then run the following commands

CAUTION: These instructions come from https://metallb.universe.tf/installation/. It is highly recommended that the user review this site thoroughly for any changes in the installation procedure before continuing. Additional configuration options can be found here: https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/example-config.yaml

* Verify the correct Kubernetes cluster is targeted: `kubectl config get-clusters` 
* Install MetalLB
----
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
# On first install only
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
----

* Create the MetalLB configuration file for layer 2 routing. See https://metallb.universe.tf/configuration/ for other routing options and https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/example-config.yaml for lots of configuration options
----
cat <<EOF> metallb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${DEFAULT_IP_RANGE_START}-${DEFAULT_IP_RANGE_END}
    - name: suse-cloud-application-platform
      protocol: layer2
      auto-assign: false
      addresses:
      - ${CAP_IP_RANGE_START}-${CAP_IP_RANGE_END}
EOF
----
** Apply the MetalLB configuration ConfigMap: `kubectl apply -f metallb-config.yaml`
*** Verify the configuration was applied correctly (especially review the IP address pool): `kubectl get configmap config -n metallb-system -o yaml`
*** Verify the MetalLB load balancer is running: `kubectl get all -n metallb-system`

### Deploy the Nginx Ingress Controller

.Source the variables file (i.e. `source ngnix-metallb.vars`), then run the following commands

* Create the nginx-ingress namespace: `kubectl create namespace nginx-ingress`
* Prepare the Base64 encoded files for the TLS secret
----
B64_CRT=$(bash -c "cat ${SVC_FQDN}.crt | base64 | awk '{print}' ORS='' && echo")
B64_KEY=$(bash -c "cat ${SVC_FQDN}.key | base64 | awk '{print}' ORS='' && echo")
----

* Create the Kubernetes secret that contains the site certificate file and private key
----
cat <<EOF> ingress-tls-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls
  namespace: nginx-ingress
data:
  tls.crt: ${B64_CRT}
  tls.key: ${B64_KEY}
type: kubernetes.io/tls
EOF
----
** Apply the Kubernetes secret: `kubectl apply -f ingress-tls-secret.yaml`

* Using Helm version 3, create the Nginx Ingress Controller
----
helm install  nginx-ingress  suse/nginx-ingress --namespace nginx-ingress --set controller.service.loadBalancerIP="${CAP_IP_RANGE_START}" --set rbac.create=true --set controller.service.externalTrafficPolicy=Local --set controller.publishService.enabled=true --set "tcp.20000=kubecf/tcp-router-tcp-router-public:20000" --set "tcp.20001=kubecf/tcp-router-tcp-router-public:20001" --set "tcp.20002=kubecf/tcp-router-tcp-router-public:20002" --set "tcp.20003=kubecf/tcp-router-tcp-router-public:20003" --set "tcp.20004=kubecf/tcp-router-tcp-router-public:20004" --set "tcp.20005=kubecf/tcp-router-tcp-router-public:20005" --set "tcp.20006=kubecf/tcp-router-tcp-router-public:20006" --set "tcp.20007=kubecf/tcp-router-tcp-router-public:20007" --set "tcp.20008=kubecf/tcp-router-tcp-router-public:20008" --set "tcp.2222=kubecf/diego-ssh-ssh-proxy-public:2222"
----

* Verify the Nginx ingress controller is communicating with the MetalLB load balancer: `kubectl get svc -n nginx-ingress`
** The ingress controller should have the first IP allocated to MetalLB and show all of the port mappings configured through Helm
*** If the ingress controller shows an EXTERNAL-IP status of <pending> for more than a few seconds, the ingress controller has not gotten the first IP address in the range. Check your variable settings and use `kubectl get svc -A` to see if the first IP address has already been taken. The ingress controller can use any valid IP address, the first IP is used here only for convenience.

### Test Nginx+MetalLB

NOTE: This test will only work if the MetalLB load balancer has at least one configured IP address that is not allocated to a cluster service

.Source the variables file (i.e. `source ngnix-metallb.vars`), then run the following commands

* Create the file containing an Nginx webserver deployment and LoadBalancer service
----
cat <<EOF> nginx-metallb-test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: ${DEFAULT_IP_RANGE_END}
EOF
----
* Create the deployment and service: `kubectl apply -f nginx-metallb-test.yaml`
* Verify the deployment is running: `kubectl get deployments,svc`
** Take note of the EXTERNAL-IP allocated to "service/nginx" 
* (OPTIONAL) Configure local DNS resolution for the IP address allocated to "service/nginx"
** Then, verify external connectivity to the nginx webserver (replace ${URL} with the actual URL): `curl http://${URL}:8080`
* Otherwise, verify external connectivity to the nginx webserver via the IP address: `curl http://${DEFAULT_IP_RANGE_END}:8080`

* When ready, delete the deployment and service: `kubectl delete -f nginx-metallb-test.yaml`
* If needed, remove the local DNS entry for the test deployment




// vim: set syntax=asciidoc:

