### This guide is meant to outline the procedure for installing the Nginx Ingress Controller and MetalLB load balancer on a running SUSE CaaS Platform installation on an on-premesis compute infrastructure. A follow on document covers installing SUSE Cloud Application Platform using these resources

NOTE: This guide follows a methodology of populating a single variables file for the entire operation and then sourcing that file at the beginning of each major step

ATTENTION: This guide assumes a SUSE CaaS Platform cluster is fully installed and running on an on-premesis compute infrastructure. May applications, including SUSE CAP, require additional resources such as a default Storage Class to be configured.

### Create and populate this variables file on the administrative workstation from which the kubectl and helm commands will be run:

----
### START Variables for creating the TSL/SSL certificates and keys ###
# Name of the root CA file. (.key will be appended to it during key creation)
export ROOTCA_NAME=
# (OPTIONAL) Document the root CA cert passphrase here or somewhere else
ROOTCA_PASSPHRASE=
## Document the values to used in creating the root CA certificate:
# Two letter country code
export COUNTRY_NAME=
# State or Province
export STATE_NAME=
# Locality or City
export LOCALITY_NAME=
# Major organization or company
export ORGANIZATION_NAME=
# OU or section
export ORGANIZATIONAL_UNIT_NAME=
# Server FQDN or service domain name, i.e. scf.caasp.local
export COMMON_NAME=
export EMAIL_ADDRESS=
# The FQDN of the external URL that clients will connect to, can be the same a COMMON_NAME in some environments
export SVC_FQDN=
### END Variables for creating the TSL/SSL certificates and keys ###

### START Variables for instantiating the MetalLB load balancer ###
# IP range is expressed as START-END, i.e. 10.0.0.10-10.0.0.19 or 10.0.0.10-10.0.0.10
export IP_RANGE=

----



### Create the TLS/SSL certificates and keys

.Source the variables file (i.e. `source <filename>`), then run the following commands

----
# Assign the passphrase
openssl genrsa -des3 -out ${ROOTCA_NAME}.key 2048
# Provide the root CA private key passphrase when prompted
openssl req -x509 -new -nodes -key ${ROOTCA_NAME}.key  -subj "/C=${COUNTRY_NAME}/ST=${STATE_NAME}/L=${LOCALITY_NAME}/O=${ORGANIZATION_NAME}/OU=${ORGANIZATIONAL_UNIT_NAME}/CN=${COMMON_NAME}/emailAddress=${EMAIL_ADDRESS}" -sha256 -days 1825 -out ${ROOTCA_NAME}.pem
# Generate the site private key
openssl genrsa -out ${SVC_FQDN}.key 2048
openssl req -new -key ${SVC_FQDN}.key -subj "/C=${COUNTRY_NAME}/ST=${STATE_NAME}/L=${LOCALITY_NAME}/O=${ORGANIZATION_NAME}/OU=${ORGANIZATIONAL_UNIT_NAME}/CN=${COMMON_NAME}/emailAddress=${EMAIL_ADDRESS}" -out ${SVC_FQDN}.csr
----
* Create the .ext file
----
cat <<EOF> ${SVC_FQDN}.ext
authorityKeyIdentifier=keyid,issuer

basicConstraints=CA:FALSE

keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment

subjectAltName = @alt_names

[alt_names]

DNS.1 = ${SVC_FQDN}

DNS.2 = *.${SVC_FQDN}

DNS.3 = uaa.${SVC_FQDN}

DNS.4 = *.uaa.${SVC_FQDN}
EOF
----
* Create the x509 cert
----
# Provide the root CA private key passphrase when prompted
openssl x509 -req -in ${SVC_FQDN}.csr -CA ${ROOTCA_NAME}.pem -CAkey ${ROOTCA_NAME}.key -CAcreateserial -out ${SVC_FQDN}.crt -days 1825 -sha256 -extfile ${SVC_FQDN}.ext
----
* (OPTIONAL) Verify the cert public key, site private key, and certificate signing request match
** The resulting md5 hashes should all be the same
----
openssl x509 -noout -modulus -in ${SVC_FQDN}.crt | openssl md5
openssl rsa -noout -modulus -in ${SVC_FQDN}.key | openssl md5
openssl req -noout -modulus -in ${SVC_FQDN}.csr | openssl md5
----


### Deploy the MetalLB load balancer

.Source the variables file (i.e. `source <filename>`), then run the following commands

CAUTION: These instructions come from https://metallb.universe.tf/installation/. It is highly recommended that the user review this site thoroughly for any changes in the installation procedure before continuing. 

* Install MetalLB
----
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
# On first install only
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

----

* Create the MetalLB configuration file for layer 2 routing. See https://metallb.universe.tf/configuration/ for other routing options
----
cat <<EOF> metallb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${IP_RANGE}
EOF
----

### Deploy the Nginx Ingress Controller


### Test Nginx+MetalLB




// vim: set syntax=asciidoc:

